### ISSUE TITLE
Measure always runs over IO

### ISSUE THREAD

**Issue by ocramz** [tonyday567/perf#6]
I don't think the `m` parameter in the Measure type is actually necessary since all measuring functions require IO. 
Also, StateT over IO (such as how PerfT is currently implemented) might not run correctly in the presence of exceptions (which the current version of the code doesn't consider). It might make more sense to use `ReaderT IO`.

**Comment by tonyday567** [comment]
After adding back in some batteries in 0.10, Measure and the library is now much more polymorphic.
